export default {
    USER_LOGGING_IN: 'USER_LOGGING_IN',
    USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    SET_NAV_SUBTITLE: 'SET_NAV_SUBTITLE',
    SET_TOKEN: 'SET_TOKEN',
    REQUEST_SCHOOLS: 'REQUEST_SCHOOLS',
    RECEIVE_SCHOOLS: 'RECEIVE_SCHOOLS',
    SELECT_STATUS: 'SELECT_STATUS'
}

